openapi: "3.0.0"
info:
  version: 0.0.1
  title: "[UN]Availability Scheduler Service"
  description: Servico responsavel por registrar agendamentos de disponibilidade/indisponibilidade dos restaurantes
servers:
  - url: http://localhost:3000

paths:
  /schedule:
    post:
      description: Registra um novo agendamento
      requestBody:
          required: true
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Schedule'
      responses:
        '201':
          description: Devolve um objeto com o ID do agendamento
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Schedule'
        default:
          description: Em caso de erro (status 4xx ou 5xx)
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
components:
  schemas:
    Schedule:
      type: object
      properties:
        id:
          description: Identificador unico do agendamento
          type: string
        start:
          description: Timestamp com a data/hora inicial do agendamento
          type: string
          format: date-time
        end:
          description: Timestamp com a data/hora final do agendamento
          type: string
          format: date-time
        type:
          description: Tipo do agendamento -  "AV" para disponível, "UN" para indisponível. Default "UN"
          type: string
          enum:
          - AV
          - UN
      required:
        - start
        - end


    Error:
      required:
        - status
        - msg
      properties:
        status:
          type: integer
        message:
          type: string
